### ISSUE TITLE
Link Never expire

### ISSUE THREAD

**Issue by sokalsondha** [JonTheWong/whmcs_autoauth#11]
sir thanks for this nice script. its working really great in my whmcs 7.2 with eauth file
only issue the link never expire. all i want is when the client click on this link from the email i want its need to expire within 15 minutes since they open the link.
but i tried even after 1 hour and the link still valid.
if the hash is making based on the timestamp then it should be expire.
this is my eauth.php file

$whmcsurl = "#############################";
$autoauthkey = "####################"; // Make sure its the same in configuration.php in your root whmcs.
$secret_key = "###################"; // Make sure its the same in your email template.
if (md5($_GET['email'].$secret_key) != $_GET['hash'])
die('LINK EXPIRED VISIT ####################### and login manually'); //dying here because hash is not equal
$email = $_GET['email']; # Clients Email Address to Login
$timestamp = time(); # Get current timestamp
$goto = "viewinvoice.php?id=".$_GET['invoice']; # Here you can set default user page
$hash = sha1($email.$timestamp.$autoauthkey); # Generate Hash
$url = $whmcsurl."?email=$email&timestamp=$timestamp&hash=$hash&goto=".urlencode($goto);
header("Location: $url");
exit;
?>

to expire the link within 15 minutes what should i change in the code?

can you please help?

**Comment by apeman76** [comment]
This is not possible from within this file, you would need to use custom php logic like in this thread: https://github.com/JonTheWong/whmcs-autoauth-invoice/issues/10

**Comment by JonTheWong** [comment]
@sokalsondha its a known bug as of now, the only solution is to change the secret key and force an expire on old emails.
