### ISSUE TITLE
How to create a hash

### ISSUE THREAD

**Issue by WebbsnacksAB** [JonTheWong/whmcs_autoauth#12]
Hi,

Could you please explain how to create a hash, and what to create a hash of?

I think i have done everything else correct, but im not being able to login via the link.

**Comment by apeman76** [comment]
I used this website to create a hash: https://onlinehashtools.com/generate-random-md5-hash?&count=2

**Comment by WebbsnacksAB** [comment]
Thank you Thomas! 

Should i copy $email.$timestamp.$autoauthkey and paste it there and then create a hash?

**Comment by apeman76** [comment]
No you use 2 of these hashes
One as system key, and one as secret key

iauth.php example:
```
Generate a hash and enter it in configuration.php above the last ?>
$autoauthkey = "MD5 hash 1";
```
```
$autoauthkey = "MD5 hash 1"; /* same as in configuration.php */
$secretkey = "MD5 hash 2"; /* generate a new key for this script */
```
```
Then add this value to the top of your email template;
{assign var='hash' value=$client_email|cat:"MD5 hash 2"}
```
```
Then add this link anywhere in your email template.
Login Auth: {$whmcs_url}lauth.php?email={$client_email}&zmkey={$hash|md5}
```

**Comment by WebbsnacksAB** [comment]
Allright, so as an example this is how it should look like:

$whmcsurl = "https://xxxxx.se/whmcs/dologin.php"; /* replace with your url */
$autoauthkey = "90b913cc3af373dfb391eceffb054dc7"; /* same as in configuration.php */
$secretkey = "5804b18e26f29e115eeeb3a472ec1e7b"; /* generate a new key for this script */

if (md5($_GET['email'].$secretkey) != $_GET['zmkey'])
die('Något har blivit fel, vänligen kontakta oss via info@webbsnacks.se för att få hjälp med problemet.');

$email = $_GET['email'];
$timestamp = time();
$hash = sha1($email.$timestamp.$autoauthkey);
$goto = "viewinvoice.php?id=".$_GET['invoice'];

$url = $whmcsurl."?email=$email&timestamp=$timestamp&hash=$hash&goto=".urlencode($goto);
header("Location: $url");
exit;
?>

**Comment by JonTheWong** [comment]
Yes
