### ISSUE TITLE
AutoAuth is deprecated as of v7.10

### ISSUE THREAD

**Issue by flexxdesign** [JonTheWong/whmcs_autoauth#13]
> The AutoAuth client login feature is now deprecated. The CreateSsoToken API is a more robust and simpler mechanism for directing users from one authenticated system to a mapped client account within your WHMCS. AutoAuth will be completely removed from WHMCS no later than v8.1.

Are you planning on modifying the scripts?

Source: https://docs.whmcs.com/Version_7.10.0_Release_Notes

**Comment by JonTheWong** [comment]
I’ll take a look into this and get back to you.

**Comment by JonTheWong** [comment]
no alternative, closing for now.
