### ISSUE TITLE
Compatibility with version 6.2.0

### ISSUE THREAD

**Issue by golifter** [JonTheWong/whmcs_autoauth#2]
Hello,
Is this module has compatibility with version 6.2.0?

Thanks

**Comment by JonTheWong** [comment]
It has been tested till 6.1.1
I'll be testing it on 6.2.0 when we have the chance, but according to the changelog on 6.2.0 it shouldn't be a problem. Nothing has changed code wise in regards to our plugin.

If you do decide to test it, please follow up with your results.

**Comment by golifter** [comment]
Hey man! Thanks!

I'll test it and and then follow up to you.
