### ISSUE TITLE
Do this from an other locaion?

### ISSUE THREAD

**Issue by dfrankes** [JonTheWong/whmcs_autoauth#3]
Is it possible to do this from an external script? outside WHMCS? (So i can do it from my panel instead of making a redirect to WHMCS)

**Comment by dfrankes** [comment]
What i want to do is, Let the user click on the invoice link in my panel, It should create the auto-login thing and after 5 minutes it will expire

**Comment by dfrankes** [comment]
I resolved the issue, Got it working

**Comment by JonTheWong** [comment]
It requires WHMCS, if you find another way. Feel free to post it.
