### ISSUE TITLE
7.2.2 working

### ISSUE THREAD

**Issue by marcpope** [JonTheWong/whmcs_autoauth#5]
Can you confirm this works with WHMCS 7.2.2? (The latest version) I was using a similar plug-in and it stopped working about 2 weeks ago when whmcs auto-upgraded and I didn't get any payments for 2 weeks! Not very fun. But my clients are driving me crazy calling and asking for their passwords.

I wasn't using this one, but a similar solution which I had to translate in English.
https://github.com/gofas/whmcs-autologin

**Comment by JonTheWong** [comment]
confirmed
