### ISSUE TITLE
modifier 'md5' not allowed by security setting

### ISSUE THREAD

**Issue by tiagocaus** [JonTheWong/whmcs_autoauth#9]
Unfortunately now this module is not working on WHMCS v7, according to
some friends. It seems that Smarty is not working with the function |md5 (from PHP).
I saw that Smarty lets you use the PHP functions and that the function |md5 is not a standard modifier, as explained in the manual (http://www.smarty.net/docs/en/language.modifiers.tpl):

Do you have any idea what to do?
Thank yo a lot for your great help!

**Comment by apeman76** [comment]
Hi, I have got this version working with 7.7.1, what version are you using? 
Did you add these rules to your configuration.php?
`$smarty_security_policy = array(
	'mail' => array(
		'php_modifiers' => array(
			'md5',
		),
	),
);`
[click here for the correct layout](https://pastebin.com/MLjEH03h)

**Comment by tiagocaus** [comment]
Hello, I'm using version 7.7.1.
Yes, I put the code in the configuration.php file
```
$smarty_security_policy = array(
    'mail' => array(
        'php_modifiers' => array(
            'escape','count','md5',
        ),
    ),
);
```

Erros:
`
Smarty Error: Syntax error in template "mailMessage:mailMessage:plaintext" on line 24 "{$whmcs_url}/autologin.php?email={$client_email}&invoice={$quote_number}&hash={$hash|md5}" modifier 'md5' not allowed by security setting
`

`Smarty Error: Syntax error in template "mailMessage:mailMessage:message" on line 42 "<p><a style="border: 1px solid #090; background-color: #dfe; text-decoration: none; font-weight: bold; padding: 15px 50px 15px 50px;" href="{$whmcs_url}/autologin.php?email={$client_email}&invoice={$quote_number}&hash={$hash|md5}" target="_blank" rel="noopener">CLIQUE AQUI PARA PAGAR</a></p>" modifier 'md5' not allowed by security setting`

**Comment by tiagocaus** [comment]
Erros:

> Smarty Error: Syntax error in template "mailMessage:mailMessage:plaintext" on line 24 "{$whmcs_url}/autologin.php?email={$client_email}&invoice={$quote_number}&hash={$hash\|md5}" modifier 'md5' not allowed by security setting

> Smarty Error: Syntax error in template "mailMessage:mailMessage:message" on line 42 "<p><a style="border: 1px solid #090; background-color: #dfe; text-decoration: none; font-weight: bold; padding: 15px 50px 15px 50px;" href="{$whmcs_url}/autologin.php?email={$client_email}&invoice={$quote_number}&hash={$hash|md5}" target="_blank" rel="noopener">CLIQUE AQUI PARA PAGAR</a></p>" modifier 'md5' not allowed by security setting

**Comment by apeman76** [comment]
That's weird. I have the exact same version and setup but there does seem to be a difference 🤔 
My email template looks like this on line 1:
```{assign var='hash' value=$client_email|cat:"<mymd5>"}```
and "this link" as text with this href:
```{$whmcs_url}eauth.php?email={$client_email}&invoice={$invoice_num}&hash={$hash|md5}```
and it does send the email:
https://i.postimg.cc/sXD2fDxd/Capture.jpg

also, I generated my md5 hashes via this URL, I do not know if this makes any difference
https://onlinehashtools.com/generate-random-md5-hash

Oh and your configuration code looks different than mine:
```
$smarty_security_policy = array(
	'mail' => array(
		'php_modifiers' => array(
			'md5',
		),
	),
);
```

**Comment by tiagocaus** [comment]
One question, in that part:
`{assign var='hash' value=$client_email|cat:"<mymd5>"}`

Is it to leave anyway?
`cat:"<mymd5>"`

**Comment by tiagocaus** [comment]
lol, now it's working!

Or was it the new MD5 that I generated from the site you sent or forgot to put md5 in "".
